### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Nightmonkee** [Aioros/destiny-reminders#2]
I try to access the website and it simply pops up a message saying "Internal Server Error." Not sure if it's my device or not. I tried on multiple browsers. Will try on a different device in a few minutes. Thought it may be helpful to bring to your attention. Good stuff anyway homie seems legit!

**Comment by Aioros** [comment]
Thank you @Nightmonkee , and sorry, that's totally my fault. I deployed a new version that was supposed to have Banshee mods, but apparently it was faulty. I reverted to a previous working revision for now, so you should be able to access the website. Let me know if there's any other issue.

**Comment by Nightmonkee** [comment]
@Aioros The website works up until I log in with Bungie. After that it says Destiny API's are unavailable right now.

**Comment by Aioros** [comment]
Thank you again @Nightmonkee . I believe I found the issue, and the new version is already deployed. It might be a little wonky for a few minutes, but it should work well after that. I suggest trying again later, and if it's still not working I will definitely get on that tomorrow.

**Comment by Nightmonkee** [comment]
You're welcome @Aioros good work I'll try it again later!

**Comment by Coconutcoo** [comment]
I'm seeing "Bungie APIs are currently unavailable, please retry later" after logging in now, perhaps related to this issue?

**Comment by Aioros** [comment]
Thanks for letting me know @Coconutcoo . It seems like I had a bad typo in one of the last updates, and it messed up login for certain D2 memberships. The issue was mostly unrelated to the other but the error message was very unhelpful, so I made sure to change that too.

I just deployed the new version, so you should be able to login correctly now. Let me know if you are still facing this issue.

**Comment by Coconutcoo** [comment]
Looks like it's working now, thanks for the quick response!
