### ISSUE TITLE
Reminder emails not being sent out?

### ISSUE THREAD

**Issue by cheers12** [Aioros/destiny-reminders#4]
I've set up a reminder for Light From Darkness mod but I didn't receive an email today?

**Comment by AgentRev** [comment]
Same, no email here.

![image](https://user-images.githubusercontent.com/1380241/104118801-a5fba980-52f9-11eb-91be-599ee6c6cc9f.png)

**Comment by TofuCrushKing** [comment]
same here. hope the other reminders work? the very reason for using this site is in jeopardy!

**Comment by Aioros** [comment]
Well, it's definitely a serious issue, my apologies to everyone. I'm still not sure what happened, as I can see quite a few emails going out for that mod yesterday, but clearly not all of them. I'll keep you posted, and I suppose I need to add some kind of warning in the meantime.

**Comment by Aioros** [comment]
Thought I'd update on this issue, since it's obviously an important one.

The issue was certainly related to the high amount of emails that had to be sent. I already deployed a tentative fix recently, and I'm quite confident about it, but unfortunately I can only confirm that the next time one of the good Banshee mods is available.

I'm going to remove the warning for now, since the core functionality of the website is ok. I'll be monitoring Banshee's mods to confirm whether this issue is resolved. Apologies again for the inconvenience.

**Comment by Aioros** [comment]
Update about this issue: today Banshee is selling Burning Cells, so I'm actively monitoring the emails being sent out. Seems like they're going out just fine at the moment, it's just fairly slow (270 emails sent over 498 after ~1hr). I fully intend to speed up the process in the future (mostly to avoid the risk of duplicate emails), but apart from that I think this is solved. If the process ends correctly I'll be closing this issue later in the day.

**Comment by cheers12** [comment]
I can confirm that I did receive an email this time

**Comment by AgentRev** [comment]
Me too!

**Comment by Aioros** [comment]
Good news everyone, I was able to identify with certainty the original issue (please don't check what it was, it's embarassing). The last batch of emails has just being sent, so I'm finally closing this issue. I'll open a new one myself for the duplicate email issue.
Thanks everyone for the info provided.

**Comment by AgentRev** [comment]
Can confirm I received today's email for Blessing Of Rasputin.
