### ISSUE TITLE
Legend or color guide on items? 

### ISSUE THREAD

**Issue by a1ex6sp** [Aioros/destiny-reminders#6]
For example, Spider has items he's already selling, which you can see by either clicking on the item or knowing the correct highlight color. Could a legend be added to speed up the process and help with pages that involve more than 2 colors?

**Comment by Aioros** [comment]
That's a good point. I originally didn't want a color guide in order to keep the UI clean on mobile, but it's not easy to figure it out, especially for vendors with dozens of possible choices. I'll see if I come up with a reasonable way to do this.
Also, just in case this info is needed:

- blue = current
- yellow = needed for some triumph/collectible
- green = both

**Comment by Aioros** [comment]
I added a row of colored buttons at the top of every list. It serves as both a legend for the two main colors, and a filter to only show current/suggested items.
